### ISSUE TITLE
Having a parameter of number of bytes to use from source buffer

### ISSUE THREAD

**Issue by purell** [alexgorbatchev/node-crc#30]
Hi,

It would be nice to have a parameters of number of bytes to use from source to compute the CRC.
Ex : 

var buffer = new Buffer(256);
for (var i = 0; i < 10; ++i) {
   buffer[i] = i;
}
var theCRC = crc.crc16modbus(buffer, 10);

This way, we don't have to call buffer.slice to compute a CRC of the first 10 bytes of this buffer and also it allow us to operate only on a subset of the buffer.

Or better, two optional parameters from/to
crc.crc16modbus(buffer, 5, 10);

Best regards,

By the way thank you for your excellent work on this library.

**Comment by alexgorbatchev** [comment]
Would you like to submit a PR?
