### ISSUE TITLE
CRC-CCITT (0x1D0F)

### ISSUE THREAD

**Issue by zachmckie** [alexgorbatchev/node-crc#31]
Would it be possible to add support for CRC-CCITT 16-bit with the initial value of 0x1D0F and a final XOR value of 0x0000? Thanks

**Comment by alexgorbatchev** [comment]
Think you could do a PR for that? I appreciate any help with the module!

**Comment by zachmckie** [comment]
Figured out that this is already supported. After looking at the crc16ccitt function definition, I noticed there was a 'previous' parameter which when set to 0x1D0F overrides the initial value of 0xFFFF.

**Comment by alexgorbatchev** [comment]
:+1:
