### ISSUE TITLE
CRC-32B? Endianness?

### ISSUE THREAD

**Issue by ptdecker** [alexgorbatchev/node-crc#32]
Hello!

Thank you for developing and maintaining node-crc.

This is probably a n00b question, but when running against a test file (below), with the code below, I receive a calculated value of 'd5e004dd'. However, when I open the file in iHex it tells me that the CRC32 should be '05ea0cdd' and that the CRC32B is 'dd04e0d5'.

Note that the value returned by node-crc does not match CRC32 but, instead, matches CRC32B with the byte order reversed.

Can someone help me understand these results?

(Note: the test file below is from an effort I'm undertaking to porting to NodeJS Nayuki Minase's approach to forcing CRC-32 values)

Code Sample:

```javascript
"use strict";
var fs = require('fs'),
    crc = require('crc');
console.log(crc.crc32(fs.readFileSync("testfile.txt", 'utf8')).toString(16));
```

testfile.txt:

```
This is a test file. The last four bytes of this file are changed to force a particular CRC value. XXXX
```

**Comment by ptdecker** [comment]
iHex is by http://www.hewbo.com/ and can be found in the OS X App Store but not, apparently (and annoyingly) from their web site.

**Comment by alexgorbatchev** [comment]
Could it be that they have it reversed? :) My hope is that pycrc that dates back to 2007 has been tested thoroughly by now.

**Comment by ptdecker** [comment]
No, nothing concrete 

---
P. Todd Decker
913-284-8814

On May 5, 2015, at 3:08 PM, Alex Gorbatchev <notifications@github.com> wrote:

Have you been able to get any insight into this?

―

**Comment by ptdecker** [comment]
LOL... So, what are the answer or insights? I suspect there must be some insights or is this just closed with none?  :-)

---
P. Todd Decker
913-284-8814

On May 5, 2015, at 4:04 PM, Alex Gorbatchev <notifications@github.com> wrote:

Closed #32.

―

**Comment by alexgorbatchev** [comment]
Not really sure what else I can do here. The CRC value produced seems to be the same, just in reverse order. It's possible that `pycrc` names differ from ihex. I'm following `pycrc` for consistency and verification.

**Comment by ptdecker** [comment]
Thank you, Alex. I'll loop back if I can figured out anything more. I appreciate your insights.

---
P. Todd Decker
913-284-8814

On May 5, 2015, at 4:15 PM, Alex Gorbatchev <notifications@github.com> wrote:

Not really sure what else I can do here. The CRC value produced seems to be the same, just in reverse order. It's possible that pycrc names differ from ihex. I'm following pycrc for consistency and verification.

―
