### ISSUE TITLE
Release tagging?

### ISSUE THREAD

**Issue by frozencemetery** [alexgorbatchev/node-crc#33]
Releases after 3.1.0 have not been tagged in git (and consequently do not appear in the "Releases" tab on Github).  Since npmjs.com strips test directories out of their tarballs, it is important to have the github tarballs as well for packaging purposes.  Could you please tag your releases?

Thanks!

**Comment by alexgorbatchev** [comment]
Must've forgot to push the tags... I'll check on my home laptop if they still might be there.

**Comment by alexgorbatchev** [comment]
Backfilled old release tags.
