### ISSUE TITLE
crc return type 

### ISSUE THREAD

**Issue by ahmed-eb** [alexgorbatchev/node-crc#40]
My understanding is that a CRC is a hash not a number. Should it return a Buffer instead of a Number type ?

**Comment by alexgorbatchev** [comment]
CRC is not a hash https://en.wikipedia.org/wiki/Cyclic_redundancy_check

**Comment by ahmed-eb** [comment]
Yes you are right that is not a hash  but it not a number too. It's more of Byte array and for this reason returning a number object doesn't make sens.
