### ISSUE TITLE
Wrong crc16-ccitt return value?

### ISSUE THREAD

**Issue by l0oky** [alexgorbatchev/node-crc#43]
Hi, `66236366675F676574400D0A` should return crc `5288`. Using the following code I get the wrong value:
```javascript
var crc16 = crc.crc16ccitt(new Buffer('66236366675F676574400D0A','hex')).toString(16); //73E1
```
Reading the documentation of how to calculate crc from this HEX and get `10F2` It said that It uses the following C code:
```c
unsigned short crc_16_rec(unsigned char * pucData, unsigned short ucLen) {
  //--------------------------------------------------------------------
  unsigned int i;
  unsigned char ucBit, ucCarry;
  //--------------------------------------------------------------------
  unsigned short usPoly = 0x8408; //reversed 0x1021
  unsigned short usCRC = 0;
  //--------------------------------------------------------------------
  for (i = 0; i < ucLen; i++) {
    usCRC ^= pucData[i];
    for (ucBit = 0; ucBit < 8; ucBit++) {
      ucCarry = usCRC & 1;
      usCRC >>= 1;
      if (ucCarry) {
        usCRC ^= usPoly;
      }
    }
  }
  return usCRC;
}
```
Is the polynimial different? Whats causing this issue?

edit:
Sorry, I've made a slight error, the result shouldn't be `0x10F2` as I've said before It should be `0x5288`

Thank you.

**Comment by l0oky** [comment]
I have a working example of this C++ code [here](http://ideone.com/795hQy).

**Comment by alexgorbatchev** [comment]
Have you tried running the same value through [pycrc](http://www.tty1.net/pycrc/)? I'm curious what the result would be.

**Comment by l0oky** [comment]
```python
from PyCRC.CRC16 import CRC16
from PyCRC.CRC16DNP import CRC16DNP
from PyCRC.CRC16Kermit import CRC16Kermit
from PyCRC.CRC16SICK import CRC16SICK
from PyCRC.CRCCCITT import CRCCCITT

#input = b'\x05d\x05\xc0\x00\x01\x00\x0c'
input = b'\x66\x23\x63\x66\x67\x5F\x67\x65\x74\x40\x0D\x0A'
print(CRC16().calculate(input))
print(CRC16DNP().calculate(input))
print(CRC16Kermit().calculate(input))
print(CRC16SICK().calculate(input))
print(CRCCCITT().calculate(input))
```
The results are:

> 30830
> 8303
> 34898
> 6672
> 63256

Whilst It should be `21128` (DEC) or `0x5288` (HEX)

**Comment by alexgorbatchev** [comment]
I'm not really sure what to suggest here... There are two possible explanations, either pycrc has wrong implementation or something is up with the example code you are using.

```
$ ./pycrc.py --check-hexstring=66236366675F676574400D0A --model=ccitt
0x73e1
```

You can also check what the C code would look like that is produced by pycrc, something like this

```
./pycrc.py --generate=c --model=ccitt --algorithm=bbb
```

There are a few other `algorithm` options available that might closer match your example.
