### ISSUE TITLE
`new Buffer` usage

### ISSUE THREAD

**Issue by joepie91** [alexgorbatchev/node-crc#45]
In [this commit](https://github.com/alexgorbatchev/node-crc/commit/3183bddef7c3f30a29f23879924b605da9641b88). the use of `Buffer` is replaced with `new Buffer`, but (despite the misleading text of the deprecation warning), the latter is deprecated as well, and shouldn't be used either, for security reasons. [This post](https://github.com/ChALkeR/notes/blob/master/Buffer-knows-everything.md) explains why.

A [polyfill](https://www.npmjs.com/package/safe-buffer) is available to use the new, safer API will still supporting older Node.js versions.

**Comment by alexgorbatchev** [comment]
Thanks! Closed by 13959018c141bcec52e771132c09519c70a14728
