### ISSUE TITLE
buffer dependency is not declared in package.json

### ISSUE THREAD

**Issue by phra** [alexgorbatchev/node-crc#53]
hi, i'm using your module in the browser and i have a problem with `buffer` dependency because it's not explicitly required by the library. i will send a PR to fix that.

**Comment by phra** [comment]
see https://github.com/alexgorbatchev/node-crc/blob/master/src/crc16_xmodem.js#L1

**Comment by MrShakes** [comment]
Same issue here, please accept pull request
