### ISSUE TITLE
 Import of crc using es6 syntax results in an undefined import after bundling with webpack

### ISSUE THREAD

**Issue by jclangst** [alexgorbatchev/node-crc#55]
Ran into this issue while bundling the ``stellar-sdk`` library. I posted an issue about it with more details here: https://github.com/stellar/js-stellar-base/issues/136

**Comment by jclangst** [comment]
So it looks like in the old build one was able to attach the whole module to an object via ``import crc from 'crc'``. Looks like that is no longer the case in 3.6.0.

**Comment by alexgorbatchev** [comment]
fixed
