### ISSUE TITLE
Conflict with a crc return

### ISSUE THREAD

**Issue by MarceloBaeza** [alexgorbatchev/node-crc#59]
Hi, 
I was trying check this string: "A000000396564341". 
I've calculated this crc with this [page](https://www.lammertbies.nl/comm/info/crc-calculation.html). The return crc-16 was 0x0D3F, if we ignore the 0x the result would be 0D3F and I consider the same string with node-crc, but the result is D3F, this library ignore 0. Why does this happend?

**Comment by coltongit** [comment]
This is because the library ignores the 0 at the beginning when dealing with anything below 0x1000. This can easily be worked around by having a 0 be inserted at the beginning of the checksum when it's anything below 0x1000.
