### ISSUE TITLE
Typescript NodeJS problems

### ISSUE THREAD

**Issue by sirlordt** [alexgorbatchev/node-crc#62]
Hello i had problems with use the library using typescript

***********************

import { Buffer } from 'buffer';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:881:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/dsistemas/Escritorio/Node_JS/19-10-2019/TypeORM-01/src/database/entity/Route.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Module.m._compile (/home/dsistemas/Escritorio/Node_JS/19-10-2019/TypeORM-01/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:962:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TypeORM-01@0.0.1 start: `ts-node src/index.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the TypeORM-01@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dsistemas/.npm/_logs/2019-10-20T21_33_40_705Z-debug.log

**Comment by oganexon** [comment]
I also have this problem with Jest 
```bash 
Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/runner/work/core/core/node_modules/crc/crc32.js:1
    import { Buffer } from 'buffer';
           ^

    SyntaxError: Unexpected token {

       8 | const buffer_1 = require("buffer");
       9 | const events_1 = require("./events");
    > 10 | const crc32_1 = tslib_1.__importDefault(require("crc/crc32"));
         |                                         ^
      11 | /**
      12 |  * Open the file. This function is mandatory.
      13 |  * @param fileName The file that will be processed.

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:1010:58)
      at Object.<anonymous> (dist/file.js:10:41)
```

**Comment by alexgorbatchev** [comment]
You need to exclude the package from transform ignore list like so:

```
transformIgnorePatterns: ['/node_modules/(?!(crc)/).*'],
```

**Comment by nvtuan305** [comment]
I have the same issue when import crc/crc16
`const crc16 = require('crc/crc16');`

Error:
```
 import { Buffer } from 'buffer';
3|AvayaAda |        ^
3|AvayaAda |
3|AvayaAda | SyntaxError: Unexpected token {
3|AvayaAda |     at Module._compile (internal/modules/cjs/loader.js:723:23)
3|AvayaAda |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
3|AvayaAda |     at Module.load (internal/modules/cjs/loader.js:653:32)
3|AvayaAda |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
3|AvayaAda |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
3|AvayaAda |     at Module.require (internal/modules/cjs/loader.js:692:17)
3|AvayaAda |     at Module.Hook._require.Module.require (/Users/nvtuan/.nvm/versions/node/v10.16.3/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:70:39)
3|AvayaAda |     at require (internal/modules/cjs/helpers.js:25:18)
```

**Comment by harrydehix** [comment]
@sirlordt  Me too. I don't use Jest so your fix doesn't work for me @alexgorbatchev. How to solve this using typescript only?

**Comment by 1xtr** [comment]
I also have this problem with my cra project. Is there a solution to this problem?

**Comment by alexgorbatchev** [comment]
I've rewritten the whole module in TypeScript with EMS and CJS being published side by side. Hopefully this problem should be addressed now.
