### ISSUE TITLE
Does not work with esbuild.

### ISSUE THREAD

**Issue by Raynos** [alexgorbatchev/node-crc#71]
Esbuild does not understand the unwrap file ( https://github.com/alexgorbatchev/node-crc/blob/91e038fe150fbf3a6da65dff58ef6aa36c59381e/dist/cjs-default-unwrap/unwrap.js ).

```
const results = module.require(path).default;
```

This dynamic use of `module.require(path)` breaks the esbuild bundler.

**Comment by alexgorbatchev** [comment]
Thanks for flagging this. Do you have a suggestion on how to fix this?

**Comment by AndrejLukasevic** [comment]
Same issue using `rollup.js`

**Comment by Raynos** [comment]
I worked around this by downgrading to an older version.

**Comment by alexgorbatchev** [comment]
I'm unable to reproduce the esbuild issue, here's the test https://github.com/alexgorbatchev/node-crc/commit/23ef3b4cd31623eb0871f945c52ec768ca70d5d4

**Comment by Raynos** [comment]
We use the following

```sh
esbuild main.js --bundle --minify false --platform node --format cjs --out bundle.js
```

And then the source code is something like

```js
const crc = require('crc')

crc.crc16(buf).toString(16)
```

Tell esbuild to bundle the commonjs entry point with their node_modules into a single commonjs file. And then execute the commonjs output file bundle.js
